[service]
name = "order"
[api]
[api.publicOrder]
prefix = "/public/v1/order"
routes = [
    "createPreOrder",
    "getPreOrder"
]
[api.privateOrder]
prefix = "/private/v1/order"
routes = [
    "createPreOrder",
    "getPreOrder"
]


[job]
StatisticDataByDay = "30 1 0 * * *"
LoopCSync = "30 1 0 * * *"

[cmd]
[cmd.createOrder]
flag = ["LoopOrder","LoopInvoice"]


[mysql]
[mysql.order]
tables = ["order","goods"]
[mysql.wallet]
tables = ["record"]

[redis]
[redis.order]